// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Tiled2UnityMac
{
	public class Tiled2UnityWindowControllerDelegate : NSWindowDelegate
	{
		public override void WillClose (NSNotification notification)
		{
			NSApplication.SharedApplication.Terminate (NSApplication.SharedApplication);
		}
	}
	
	public partial class Tiled2UnityWindowController : NSWindowController
	{
		public Tiled2UnityWindowController (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			this.Window.Delegate = new Tiled2UnityWindowControllerDelegate ();
		}
			
	}
}
